<section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Please add or remove items</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center setCenter">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
                        <h3>Add item</h3>
                        <p class="text-muted">Add new item to your personal list.</p><input class="button" type="text" id="add" /><button class="button" id="buttonAdd">Add</button>
                    </div>
                </div>                
            </div>
        </div>
    </section>    
    <aside class="bg-dark">
        <div class="container text-center">            
            <div class="call-to-action setCenter" id="itemsList">                
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>
