<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport"    content="width=device-width, initial-scale=1.0" />        
        <title>Arkadiusz Mazur - error site</title> 
        <?php  
            $baseUrl = '/public/';            
            $cssFiles = $this->headLink()->appendStylesheet($baseUrl.'vendor/bootstrap/css/bootstrap.min.css') 
                    ->headLink()->appendStylesheet($baseUrl.'vendor/bootstrap/css/fonts.css') //custom fonts
                    ->headLink()->appendStylesheet($baseUrl.'vendor/font-awesome/css/font-awesome.min.css')
                    ->headLink()->appendStylesheet($baseUrl.'css/creative.min.css'); //theme               

            echo $cssFiles;
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        
        <style>
            .errorLink {color:black;}
        </style>
    </head>    

<body id="page-top">   

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">                                                            
                    <h2 class="section-heading">Something went wrong :(</h2>                    
                    <hr class="light">
                    <p class="text-faded"><?php echo $this->layout()->content ?></p>                    
                    <h4><a href="/" class="errorLink">&laquo; Click here to go back to main page</a></h4>
                </div>
            </div>
        </div>
    </section>                  