<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport"    content="width=device-width, initial-scale=1.0" />
        <link rel="Shortcut icon" href="/images/favicon.ico" />
        <title>Arkadiusz Mazur</title> 
        <?php  
            $baseUrl = '/public/';            
            $cssFiles = $this->headLink()->appendStylesheet($baseUrl.'vendor/bootstrap/css/bootstrap.min.css') 
                    ->headLink()->appendStylesheet($baseUrl.'vendor/bootstrap/css/fonts.css') //custom fonts                    
                    ->headLink()->appendStylesheet($baseUrl.'vendor/font-awesome/css/font-awesome.min.css')
                    ->headLink()->appendStylesheet($baseUrl.'css/creative.min.css') //theme               
                    ->headLink()->appendStylesheet($baseUrl.'css/app.css');

            echo $cssFiles;

            $jsFiles = $this
                            //->headScript()->prependFile($baseUrl.'js/creative.min.js') //theme
                            ->headScript()->prependFile($baseUrl.'js/app.js') //my script
                            ->headScript()->prependFile($baseUrl.'vendor/scrollreveal/scrollreveal.min.js') //plugin
                            ->headScript()->prependFile($baseUrl.'vendor/jquery/jquery-easing.min.js') //plugin
                            ->headScript()->prependFile($baseUrl.'vendor/bootstrap/js/bootstrap.min.js') //bootstrap core
                            ->headScript()->prependFile($baseUrl.'vendor/jquery/jquery.min.js'); //jquery                                                                                                                
            echo $jsFiles;
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>    

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#services">Add/remove items</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Author</a>
                    </li>
                    <li>
                        <a class="page-scroll" id="logout" href="/logout">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    
                        <div>
                            <?php
                            //Flash Messenger                                                               
                            if (is_array($this->messages))
                                foreach ($this->messages as $message) {
                                        ?>
                                        <div id="flashMessenger">                                                                                        
                                            <?php echo $message; ?>                                            
                                        </div>    
                                        <?php                                    
                                }
                            ?>                                                                                                                                                                                                                                                                                                                                                                                                        
                        </div>                    
                                        
                    <h2 class="section-heading">Arkadiusz Mazur - task from Edukey</h2>
                    <hr class="light">
                    <p class="text-faded">Hi user: <i>amazur.edukey@gmail.com</i>. Here you can add and remove items to your personal list. </p>                    
                </div>
            </div>
        </div>
    </section>
    
    <?php echo $this->layout()->content ?>   

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Arkadiusz Mazur - contact</h2>                    
                    <hr class="primary">                    
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>Skype: programista.php.sql</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:arkadiusz.mazur@hotmail.com">arkadiusz.mazur@hotmail.com</a></p>
                </div>
            </div>
        </div>
    </section>
